nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD']
        allow_headers: ['*']
        max_age: 360000

    paths:
        '^/': ~
